-- Regenerate both synthetic spellings from addon builders and compare the
-- established byte contract. Run from tests/ with a disposable output directory.
local addonPath, outputDirectory = ...
assert(addonPath and outputDirectory,
    "usage: lua test_schema2_generation.lua ../MclarionWow.lua <scratch-directory>")
local generate = assert(loadfile("generate_schema2_fixture.lua"))
local function read(path)
    local file = assert(io.open(path, "rb"))
    local bytes = assert(file:read("*a"))
    assert(file:close())
    return bytes
end
for _, variant in ipairs({ "implicit", "explicit" }) do
    -- A previous suite may leave no items or a different schema. Neither
    -- should contribute a byte to this builder-only fixture.
    MclarionWowData = variant == "implicit" and { schema = 3 } or
        { schema = 2, items = {} }
    local generated = outputDirectory .. "/schema2-" .. variant .. ".lua"
    generate(addonPath, generated, variant)
    local expected = variant == "implicit" and "schema2-synthetic.lua" or
        "schema2-synthetic-explicit.lua"
    assert(read(generated) == read(expected), variant .. " generated bytes drifted from the synthetic contract")
end
assert(loadfile("test_schema2_fixture.lua"))(outputDirectory .. "/schema2-implicit.lua")
assert(loadfile("test_schema2_fixture_pair.lua"))(
    outputDirectory .. "/schema2-implicit.lua", outputDirectory .. "/schema2-explicit.lua")
print("fresh synthetic fixtures match both checked-in spellings byte-for-byte")
